export const words = {
  en: {
    home: "Mobile companion",
    all: "All topics",
    conversations: "Topics",
    conversationHint: "Proposals, decisions, and documents grouped by topic.",
    openActions: "Open actions for",
    closeActions: "Close actions for",
    pinConversation: "Pin",
    unpinConversation: "Unpin",
    deleteConversation: "Delete",
    holdDelete: "Hold to delete",
    holdHint: "Hold for 1.5 seconds",
    confirmDelete: "Confirm deletion of",
    pressAgain: "Press again to confirm",
    conversationDeleted: "Topic removed from the list.",
    undo: "Undo",
    conversation: "Topic",
    empty: "No episodes in this topic yet.",
    emptyConversation: "No updates yet",
    menu: "Open menu",
    closeMenu: "Close menu",
    showRail: "Show topics panel",
    hideRail: "Hide topics panel",
    apps: "Apps",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    accent: "Accent",
    blue: "Blue",
    violet: "Violet",
    backToItem: "Back to item",
    channel: "Project",
    latest: "Latest update",
    read: "Read update",
    feed: "Episodes",
    open: "Open app",
    back: "Back to topic",
    backToList: "Back to topics",
    document: "Read document",
    submit: "Send response",
    sent: "Response sent",
    loading: "Loading…",
    updatePending: "An update is ready. Finish or leave the form to reload.",
    retry: "Try again",
    required: "Required",
    answer: "Your response",
    unavailable: "Unavailable",
    more: "Older items",
    previousVersion: "Read previous version",
    currentVersion: "Current version",
    articleHistory: "Version history",
    historicalVersion: "Historical version",
    changed: "This item has already been answered. Refresh to see the response.",
    notifications: "Phone notifications",
    notificationHelp: "Get an alert when a new update is published.",
    notificationOn: "On",
    notificationOff: "Enable",
    notificationBlocked: "Blocked in browser settings",
    notificationUnsupported: "Unavailable in this browser",
  },
  fr: {
    home: "Compagnon mobile",
    all: "Tous les sujets",
    conversations: "Sujets",
    conversationHint: "Propositions, décisions et documents rassemblés par sujet.",
    openActions: "Ouvrir les actions de",
    closeActions: "Fermer les actions de",
    pinConversation: "Épingler",
    unpinConversation: "Désépingler",
    deleteConversation: "Supprimer",
    holdDelete: "Maintenir pour supprimer",
    holdHint: "Maintenir 1,5 seconde",
    confirmDelete: "Confirmer la suppression de",
    pressAgain: "Appuyer encore pour confirmer",
    conversationDeleted: "Sujet retiré de la liste.",
    undo: "Annuler",
    conversation: "Sujet",
    empty: "Aucun épisode dans ce sujet.",
    emptyConversation: "Aucune actualité",
    menu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    showRail: "Afficher le panneau des sujets",
    hideRail: "Masquer le panneau des sujets",
    apps: "Applications",
    appearance: "Apparence",
    light: "Clair",
    dark: "Sombre",
    accent: "Couleur",
    blue: "Bleu",
    violet: "Violet",
    backToItem: "Retour à l’élément",
    channel: "Sujet",
    latest: "Dernière actualité",
    read: "Lire l’actualité",
    feed: "Épisodes",
    open: "Ouvrir l’application",
    back: "Retour au sujet",
    backToList: "Retour aux sujets",
    document: "Lire le document",
    submit: "Envoyer la réponse",
    sent: "Réponse envoyée",
    loading: "Chargement…",
    updatePending: "Une mise à jour est prête. Terminez ou quittez le formulaire pour l’afficher.",
    retry: "Réessayer",
    required: "Obligatoire",
    answer: "Votre réponse",
    unavailable: "Indisponible",
    more: "Éléments précédents",
    previousVersion: "Lire la version précédente",
    currentVersion: "Version actuelle",
    articleHistory: "Historique des versions",
    historicalVersion: "Version historique",
    changed: "Cet élément a déjà reçu une réponse. Actualisez pour la voir.",
    notifications: "Notifications sur le téléphone",
    notificationHelp: "Recevoir une alerte lorsqu’une actualité est publiée.",
    notificationOn: "Activées",
    notificationOff: "Activer",
    notificationBlocked: "Bloquées dans le navigateur",
    notificationUnsupported: "Indisponibles dans ce navigateur",
  },
};
